name: Update Podman-io on Snapcraft
on:
  push:
    branches:
      - "main"
    paths:
      - "podman-io/**"

jobs:
  build:
    runs-on: ubuntu-latest

    # Checkout Branch
    steps:
      - uses: actions/checkout@v2

      - name: Build snap
        uses: snapcore/action-build@v1
        id: build
        with:
          path: podman-io

      - name: Release snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
